various
- fix updateAssignment
- print solution as valid CNF, so that one can verify the solution by appending it to the original problem
- Verify solutions with Kissat
- Refactor duplicated code

diff --git a/test b/test
--- a/test
+++ b/test
@@ -7,4 +7,15 @@ for testfile in tests/*.cnf; do
     [ -e "$testfile" ] || continue
     echo "---- $testfile ----"
     time ./sat $testfile > ${testfile/cnf/out} 2> /dev/null
+    if grep -Fxq "UNSAT" ${testfile/cnf/out}
+    then
+        echo "Solver claims UNSAT"
+    else
+        echo "verify solution with kissat"
+        cat $testfile ${testfile/cnf/out} | ./kissat --relaxed > /dev/null
+        if [ $? -ne 10 ]; then
+            echo "KISSAT verification failed"
+            exit 1
+        fi
+    fi
 done
